---

#
# BIND - nameserver
#
- name: Install bind9
  apt: pkg=bind9 state=latest

- name: Ensure bind9 is disabled
  service: name=bind9 enabled=no

#
# postfix
#
- name: Install postfix
  apt: pkg=postfix state=latest

- name: Copy postfix.cf
  copy: src=../files/postfix-main.cf dest=/etc/postfix/main.cf owner=root group=root mode=644
  notify: restart postfix

#
# nginx
#
- name: Install nginx
  apt: pkg=nginx state=latest

- name: Copy nginx.conf
  copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify: restart nginx

- name: Ensure nginx is enabled
  service: name=nginx enabled=yes

#
# mysql
#
- name: Install mysql
  apt: pkg=mysql-server-5.6 state=latest

- name: Copy my.cnf
  copy: src=../files/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=644
  notify: restart mysql

#
# redis
#
- name: Install redis
  apt: pkg=redis-server state=latest

#
# Go
#
- name: Download Go .tgz
  get_url: url=https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz dest=/usr/local/src/go1.2.2.linux-amd64.tar.gz
  register: go_tgz

- name: Unpack Go
  shell: >
    /bin/rm -rf /usr/local/go &&
    /bin/tar zxf /usr/local/src/go1.2.2.linux-amd64.tar.gz -C /usr/local &&
    /bin/mkdir -p /usr/local/gopath  &&
    /bin/chmod 755 /usr/local/gopath  &&
    /bin/mkdir -p /var/www  &&
    /bin/chown www-data /var/www
  when: go_tgz.changed

#
# other misc deps
#
- name: Install misc apt packages
  action: apt pkg={{ item }} state=latest
  with_items:
    - ruby
    - python-pip
    - git
    - mercurial
    - nodejs
    - npm
    - node-uglify
    - python-virtualenv
    - python-epydoc
    - openjdk-7-jdk
    - maven
    - php5-cli
    - php5-curl

- name: Install jshint, mocha, and docco
  shell: >
    /usr/bin/update-alternatives --install /usr/bin/node node /usr/bin/nodejs 99 &&
    /usr/bin/npm install jshint -g &&
    /usr/bin/npm install docco -g &&
    /usr/bin/npm install mocha -g &&
    /usr/bin/gem install sinatra
